services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - php-app

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: phpDB
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_USER: root_docker
    volumes:
      - db_phpdata:/var/lib/mysql
    ports:
      - 33060:3306
    networks:
      - php-app

networks:
  php-app:
    driver: bridge

volumes:
  db_phpdata:
